In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
data=pd.read_csv("QVI_data.csv");

In [3]:
data.head()

,LYLTY_CARD_NBR,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,1000,2018-10-17,1,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175,NATURAL,YOUNG SINGLES/COUPLES,Premium
1,1002,2018-09-16,1,2,58,Red Rock Deli Chikn&Garlic Aioli 150g,1,2.7,150,RRD,YOUNG SINGLES/COUPLES,Mainstream
2,1003,2019-03-07,1,3,52,Grain Waves Sour Cream&Chives 210G,1,3.6,210,GRNWVES,YOUNG FAMILIES,Budget
3,1003,2019-03-08,1,4,106,Natural ChipCo Hony Soy Chckn175g,1,3.0,175,NATURAL,YOUNG FAMILIES,Budget
4,1004,2018-11-02,1,5,96,WW Original Stacked Chips 160g,1,1.9,160,WOOLWORTHS,OLDER SINGLES/COUPLES,Mainstream

In [9]:
store77=data[data['STORE_NBR']==77]
store77.reset_index(drop=True, inplace=True)
store77

,LYLTY_CARD_NBR,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,77000,2019-03-28,77,74911,18,Cheetos Chs & Bacon Balls 190g,1,3.3,190,CHEETOS,MIDAGE SINGLES/COUPLES,Budget
1,77000,2019-04-13,77,74912,69,Smiths Chip Thinly S/Cream&Onion 175g,1,3.0,175,SMITHS,MIDAGE SINGLES/COUPLES,Budget
2,77000,2018-09-26,77,74910,36,Kettle Chilli 175g,2,10.8,175,KETTLE,MIDAGE SINGLES/COUPLES,Budget
3,77001,2019-02-27,77,74913,7,Smiths Crinkle Original 330g,2,11.4,330,SMITHS,YOUNG FAMILIES,Mainstream
4,77001,2019-01-21,77,74914,9,Kettle Tortilla ChpsBtroot&Ricotta 150g,2,9.2,150,KETTLE,YOUNG FAMILIES,Mainstream
...,...,...,...,...,...,...,...,...,...,...,...,...
558,2330321,2018-07-30,77,236756,71,Twisties Cheese Burger 250g,2,8.6,250,TWISTIES,YOUNG SINGLES/COUPLES,Mainstream
559,2330331,2018-11-18,77,236760,95,Sunbites Whlegrn Crisps Frch/Onin 90g,2,3.4,90,SUNBITES,RETIREES,Budget
560,2330431,2018-07-31,77,236770,50,Tostitos Lightly Salted 175g,1,4.4,175,TOSTITOS,OLDER SINGLES/COUPLES,Mainstream
561,2330461,2018-07-21,77,236777,87,Infuzions BBQ Rib Prawn Crackers 110g,1,3.8,110,INFUZIONS,OLDER FAMILIES,Budget
562,2330501,2019-06-20,77,236780,63,Kettle 135g Swt Pot Sea Salt,1,4.2,135,KETTLE,OLDER SINGLES/COUPLES,Budget

import math

In [10]:
import math

In [14]:
TOT_SALES77 = store77['TOT_SALES'].sum()
print(TOT_SALES77)

3040.0

In [25]:
Total_Customers_77 = len(store77['LYLTY_CARD_NBR'].value_counts())

In [26]:
Total_Customers_77

356

In [27]:
print(store77['TXN_ID'].value_counts())

TXN_ID
75395     2
74911     1
75285     1
75284     1
75287     1
         ..
75094     1
75093     1
75090     1
75092     1
236780    1
Name: count, Length: 562, dtype: int64

In [28]:
Average_No_Of_Transactions_per_customer_77 = 562/356

In [29]:
print(Average_No_Of_Transactions_per_customer_77)

1.5786516853932584

In [30]:
store86=data[data['STORE_NBR']==86]
store86.reset_index(drop=True, inplace=True)
store86

,LYLTY_CARD_NBR,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,86000,2018-08-26,86,84137,90,Tostitos Smoked Chipotle 175g,2,8.8,175,TOSTITOS,YOUNG FAMILIES,Premium
1,86000,2018-09-25,86,84138,88,Kettle Honey Soy Chicken 175g,2,10.8,175,KETTLE,YOUNG FAMILIES,Premium
2,86000,2019-02-19,86,84139,41,Doritos Salsa Mild 300g,2,5.2,300,DORITOS,YOUNG FAMILIES,Premium
3,86000,2018-11-20,86,84140,111,Smiths Chip Thinly Cut Original 175g,2,6.0,175,SMITHS,YOUNG FAMILIES,Premium
4,86000,2018-11-30,86,84141,13,Red Rock Deli Thai Chilli&Lime 150g,2,5.4,150,RRD,YOUNG FAMILIES,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...
1533,155479,2018-08-19,86,155508,74,Tostitos Splash Of Lime 175g,2,8.8,175,TOSTITOS,NEW FAMILIES,Mainstream
1534,155479,2018-11-21,86,155509,9,Kettle Tortilla ChpsBtroot&Ricotta 150g,2,9.2,150,KETTLE,NEW FAMILIES,Mainstream
1535,155485,2018-11-08,86,155552,97,RRD Salt & Vinegar 165g,2,6.0,165,RRD,OLDER SINGLES/COUPLES,Mainstream
1536,155489,2018-08-15,86,155582,78,Thins Chips Salt & Vinegar 175g,2,6.6,175,THINS,RETIREES,Premium
1537,155510,2018-08-14,86,155718,82,Smith Crinkle Cut Mac N Cheese 150g,2,5.2,150,SMITHS,YOUNG FAMILIES,Mainstream

In [31]:
TOT_SALES86 = store86['TOT_SALES'].sum()
print(TOT_SALES86)

10635.35

In [32]:
Total_Customers_86 = len(store86['LYLTY_CARD_NBR'].value_counts())

In [33]:
Total_Customers_86

273

In [34]:
print(store86['TXN_ID'].value_counts())

TXN_ID
85074     2
84832     2
85187     2
84707     2
84649     2
         ..
84661     1
84660     1
84659     1
84658     1
155718    1
Name: count, Length: 1526, dtype: int64

In [35]:
Average_No_Of_Transactions_per_customer_86 = 1526/273

In [36]:
print(Average_No_Of_Transactions_per_customer_86)

5.589743589743589

In [37]:
store88=data[data['STORE_NBR']==88]
store88.reset_index(drop=True, inplace=True)
store88

,LYLTY_CARD_NBR,DATE,STORE_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND,LIFESTAGE,PREMIUM_CUSTOMER
0,88000,2018-09-12,88,86220,4,Dorito Corn Chp Supreme 380g,2,13.0,380,DORITOS,MIDAGE SINGLES/COUPLES,Budget
1,88000,2018-10-26,88,86221,31,Infzns Crn Crnchers Tangy Gcamole 110g,2,7.6,110,INFUZIONS,MIDAGE SINGLES/COUPLES,Budget
2,88000,2019-02-02,88,86222,46,Kettle Original 175g,2,10.8,175,KETTLE,MIDAGE SINGLES/COUPLES,Budget
3,88000,2019-05-01,88,86223,47,Doritos Corn Chips Original 170g,2,8.8,170,DORITOS,MIDAGE SINGLES/COUPLES,Budget
4,88000,2019-05-02,88,86224,102,Kettle Mozzarella Basil & Pesto 175g,2,10.8,175,KETTLE,MIDAGE SINGLES/COUPLES,Budget
...,...,...,...,...,...,...,...,...,...,...,...,...
1868,2370701,2018-12-08,88,240378,24,Grain Waves Sweet Chilli 210g,2,7.2,210,GRNWVES,YOUNG FAMILIES,Mainstream
1869,2370751,2018-10-01,88,240394,60,Kettle Tortilla ChpsFeta&Garlic 150g,2,9.2,150,KETTLE,YOUNG FAMILIES,Premium
1870,2370961,2018-10-24,88,240480,70,Tyrrells Crisps Lightly Salted 165g,2,8.4,165,TYRRELLS,OLDER FAMILIES,Budget
1871,2370961,2018-10-27,88,240481,65,Old El Paso Salsa Dip Chnky Tom Ht300g,2,10.2,300,OLD,OLDER FAMILIES,Budget
1872,2373711,2018-12-14,88,241815,16,Smiths Crinkle Chips Salt & Vinegar 330g,2,11.4,330,SMITHS,YOUNG SINGLES/COUPLES,Mainstream

In [38]:
TOT_SALES88 = store88['TOT_SALES'].sum()
print(TOT_SALES88)

16333.25

In [39]:
Total_Customers_88 = len(store88['LYLTY_CARD_NBR'].value_counts())

In [40]:
Total_Customers_88

388

In [41]:
print(store88['TXN_ID'].value_counts())

TXN_ID
86238     2
86657     2
87415     2
86954     2
87259     2
         ..
86858     1
86857     1
86856     1
86855     1
241815    1
Name: count, Length: 1857, dtype: int64

In [42]:
Average_No_Of_Transactions_per_customer_88 = 1857/388

In [43]:
print(Average_No_Of_Transactions_per_customer_88)

4.786082474226804